"""
PROBE-suite dataclasses.

Mirrors AEGIS conventions where applicable (e.g. payload library dataclasses
in the existing five suites). The session is the unit of analysis for PROBE,
in contrast to the (payload_id, mas_id, phase) triplet used by static suites.

See RFC § 4.1 and § 5.2.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Optional


class ProbeOutcomeReason(str, Enum):
    """Why a session terminated. Reported in the CSV `terminated_reason` column."""

    SUCCESS = "success"
    BUDGET_EXCEEDED = "budget_exceeded"
    ATTACKER_SELF_ABANDONED = "attacker_self_abandoned"
    VICTIM_CRASHED = "victim_crashed"
    ATTACKER_CRASHED = "attacker_crashed"
    JUDGE_UNAVAILABLE = "judge_unavailable"


class TurnVerdict(str, Enum):
    """Per-turn judge verdict from success_evaluator."""

    NO_PROGRESS = "no_progress"
    PARTIAL_PROGRESS = "partial_progress"
    SUCCESS = "success"


@dataclass(frozen=True)
class ProbeObjective:
    """
    Natural-language statement of what the attacker is trying to make the victim do.

    PROBE intentionally stores objectives, not payloads — payloads are generated by
    the attacker MAS at runtime, conditioned on objective + observation history.

    Fields mirror the static-suite payload dataclasses (`payload_id`, `severity`)
    plus PROBE-specific additions for cross-suite analysis.

    Attributes:
        objective_id:
            Globally unique within the objective library. Convention: `pr_<harm>_<n>`.
        harm_class:
            HarmBench-aligned category.
        severity:
            One of "low", "medium", "high". Mirrors static-suite severity.
        objective_text:
            What the attacker is trying to achieve, in natural language.
        success_criterion:
            Concrete textual description of what counts as success — fed to the
            Tier 3 judge prompt.
        target_agent_role:
            Optional. If set, restricts the planner to attacking the named role.
            None ⇒ attacker free to choose.
        notes:
            Free-text. Not used at runtime.
    """

    objective_id: str
    harm_class: str
    severity: str
    objective_text: str
    success_criterion: str
    target_agent_role: Optional[str] = None
    notes: str = ""

    def __post_init__(self) -> None:
        if self.severity not in ("low", "medium", "high"):
            raise ValueError(
                f"ProbeObjective.severity must be one of "
                f'{{"low","medium","high"}}; got {self.severity!r}'
            )


@dataclass
class AttackIntent:
    """
    Output of the planner node, input to the payload_crafter node.

    Distinguishes the *strategy decision* (what angle to try) from the
    *concrete realization* (the actual prompt text). This separation is what
    lets us swap policies without changing the payload-crafting logic.
    """

    target_agent_role: str
    attack_angle: (
        str  # e.g. "appeal-to-authority", "satirical-framing", "context-flooding"
    )
    rationale: str  # planner's stated reason for choosing this angle
    rung_index: Optional[int] = None  # for Crescendo-style policies; None otherwise


@dataclass
class ProbeTurn:  # pylint: disable=too-many-instance-attributes  # session log row: every field is a directly serialized result of one turn
    """One turn in a multi-turn session."""

    turn_index: int
    intent: AttackIntent
    payload_text: str
    victim_output: dict[str, Any]  # full victim MAS state snapshot
    propagation_path: list[str]  # from AEGIS PropagationTracker
    influenced_agents: list[str]
    observation_summary: str  # output of victim_observer node
    verdict: TurnVerdict
    tier3_score: int  # 0-3 per AEGIS convention
    tier3_reasoning: str
    tier3_confidence: str  # "low"/"medium"/"high"
    duration_ms: float
    tokens_attacker: int
    tokens_victim: int
    tokens_judge: int


@dataclass
class ProbeOutcome:  # pylint: disable=too-many-instance-attributes  # session footer: outcome reason + 4 aggregated numeric axes
    """Final session-level outcome."""

    reason: ProbeOutcomeReason
    final_tier3_score: int  # max across turns
    turns_to_compromise: Optional[int]  # turn_index where max score first reached
    total_duration_ms: float
    total_tokens_attacker: int
    total_tokens_victim: int
    total_tokens_judge: int
    estimated_cost_usd: float


# Cross-suite CSV columns (kept in sync with `_CSV_COLUMNS` in
# bili/aegis/suites/_suite_runner.py). PROBE rows leave `payload_id` and
# `phase` blank.
_CROSS_SUITE_COLUMNS: tuple[str, ...] = (
    "payload_id",
    "injection_type",
    "severity",
    "stub_mode",
    "mas_id",
    "phase",
    "tier1_pass",
    "tier2_influenced",
    "tier2_resistant",
    "tier3_score",
    "tier3_confidence",
    "tier3_reasoning",
    "attack_suite",
)

# PROBE-specific columns added on top of the cross-suite schema. Public so
# downstream consumers (notably ``test_probe_structural``) can reuse the
# canonical list instead of redeclaring it.
PROBE_SPECIFIC_COLUMNS: tuple[str, ...] = (
    "session_id",
    "objective_id",
    "policy",
    "rng_seed",
    "turns_used",
    "budget_used",
    "turns_to_compromise",
    "terminated_reason",
)

PROBE_CSV_COLUMNS: tuple[str, ...] = _CROSS_SUITE_COLUMNS + PROBE_SPECIFIC_COLUMNS


def _stringify_enums(obj: Any) -> Any:
    """Recursively convert Enum instances to their .value strings."""
    if isinstance(obj, Enum):
        return obj.value
    if isinstance(obj, dict):
        return {k: _stringify_enums(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_stringify_enums(v) for v in obj]
    if isinstance(obj, tuple):
        return [_stringify_enums(v) for v in obj]
    return obj


@dataclass
class ProbeSession:  # pylint: disable=too-many-instance-attributes  # session-level data container; matches execution_result.py convention
    """A multi-turn dialogue between attacker MAS and victim MAS."""

    session_id: str
    objective: ProbeObjective
    victim_mas_id: str
    victim_mas_path: str
    policy_name: str
    rng_seed: int
    attacker_model_config: dict[str, Any]
    judge_model_config: dict[str, Any]
    victim_model_config: dict[str, Any] = field(default_factory=dict)
    turns: list[ProbeTurn] = field(default_factory=list)
    final_outcome: Optional[ProbeOutcome] = None

    def to_csv_row(self) -> dict[str, Any]:
        """
        Render as a CSV row matching the cross-suite AEGIS schema.

        Per RFC § 14: 13 shared columns kept, 8 PROBE-specific columns
        appended. PROBE leaves `payload_id` and `phase` blank; static
        suites leave the PROBE columns blank.

        `tier3_score` is the MAX across `self.turns`. `tier3_reasoning`
        and `tier3_confidence` come from the (first) turn achieving the
        max score. `tier2_influenced` and `tier2_resistant` are
        JSON-encoded sorted unions across turns; `tier2_resistant` is
        derived per-turn as ``propagation_path − influenced_agents``.

        Raises:
            RuntimeError: if `final_outcome` is None (session not finalized).
        """
        if self.final_outcome is None:
            raise RuntimeError(
                f"Cannot serialize session {self.session_id!r} to CSV row: "
                "final_outcome is None (session not yet finalized)."
            )

        if self.turns:
            max_score = max(t.tier3_score for t in self.turns)
            max_turn = next(t for t in self.turns if t.tier3_score == max_score)
            tier3_reasoning = max_turn.tier3_reasoning
            tier3_confidence = max_turn.tier3_confidence
            influenced_union = sorted(
                {a for t in self.turns for a in t.influenced_agents}
            )
            resistant_union = sorted(
                {
                    a
                    for t in self.turns
                    for a in t.propagation_path
                    if a not in set(t.influenced_agents)
                }
            )
        else:
            max_score = 0
            tier3_reasoning = ""
            tier3_confidence = ""
            influenced_union = []
            resistant_union = []

        # stub_mode: attacker without a real model_name ⇒ stub run
        stub_mode = (
            "stub" if not self.attacker_model_config.get("model_name") else "real"
        )

        tier1_pass = (
            "true"
            if self.final_outcome.reason == ProbeOutcomeReason.SUCCESS
            else "false"
        )

        ttc: Any = (
            self.final_outcome.turns_to_compromise
            if self.final_outcome.turns_to_compromise is not None
            else ""
        )

        return {
            # Cross-suite columns (13)
            "payload_id": "",
            "injection_type": self.objective.harm_class,
            "severity": self.objective.severity,
            "stub_mode": stub_mode,
            "mas_id": self.victim_mas_id,
            "phase": "",
            "tier1_pass": tier1_pass,
            "tier2_influenced": json.dumps(influenced_union),
            "tier2_resistant": json.dumps(resistant_union),
            "tier3_score": max_score,
            "tier3_confidence": tier3_confidence,
            "tier3_reasoning": tier3_reasoning,
            "attack_suite": "probe",
            # PROBE-specific columns (8)
            "session_id": self.session_id,
            "objective_id": self.objective.objective_id,
            "policy": self.policy_name,
            "rng_seed": self.rng_seed,
            "turns_used": len(self.turns),
            "budget_used": self.final_outcome.estimated_cost_usd,
            "turns_to_compromise": ttc,
            "terminated_reason": self.final_outcome.reason.value,
        }

    def to_sidecar_json(self) -> dict[str, Any]:
        """Full multi-turn trajectory for `results/{mas_id}/sessions/{session_id}.json`.

        Returns a dict suitable for `json.dumps(..., default=str)`. All
        `Enum` values are pre-converted to their `.value` strings so that
        a plain `json.dumps(...)` round-trips even without a `default`
        argument. `victim_output` dicts inside `turns` may still contain
        non-JSON-native objects (e.g. LangChain messages); callers that
        want a clean round-trip should pass `default=str` to `json.dumps`.
        """
        return _stringify_enums(asdict(self))
